name: Select Subject

on:
    workflow_dispatch:
        inputs:
            subject:
                description: 'Select a subject'
                required: true
                default: 'english'
                type: choice
                options:
                    - english
                    - science
                    - social
                    - maths

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Display selected subject
            run: echo "Selected subject is ${{ github.event.inputs.subject }}"
